apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hl-api
spec:
  rules:
    - host: go.local
      http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: hl-api-service
                port:
                  number: 80